In [21]:
# Import Required Libraries
import pandas as pd
import numpy as np

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

In [22]:
# Load dataset
df = pd.read_csv("../dataset/processed/airline_delay_selected.csv",encoding="latin1")

In [23]:
# Display the first five rows
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,DepDelay,DepDelayMinutes,ArrDelay,ArrDelayMinutes,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Cancelled,CancellationCode,Diverted,Distance,DistanceGroup
0,1998,1,1,2,5,1998-01-02,NW,MSP,"Minneapolis, MN",MN,SLC,"Salt Lake City, UT",UT,19.0,19.0,23.0,23.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,991.0,4
1,2009,2,5,28,4,2009-05-28,FL,MKE,"Milwaukee, WI",WI,MCO,"Orlando, FL",FL,-2.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,1066.0,5
2,2013,2,6,29,6,2013-06-29,MQ,GJT,"Grand Junction, CO",CO,DFW,"Dallas/Fort Worth, TX",TX,14.0,14.0,-3.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,773.0,4
3,2010,3,8,31,2,2010-08-31,DL,LAX,"Los Angeles, CA",CA,DTW,"Detroit, MI",MI,0.0,0.0,-20.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,1979.0,8
4,2006,1,1,15,7,2006-01-15,US,EWR,"Newark, NJ",NJ,CLT,"Charlotte, NC",NC,51.0,51.0,32.0,32.0,0.0,0.0,0.0,0.0,32.0,0.0,NaN,0.0,529.0,3

In [24]:
#Shape of the dataset
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

Rows    : 2,000,000
Columns : 27

In [25]:
# Missing Values
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": round(df.isnull().mean()*100,2)
})

missing = missing[missing["Missing Values"]>0]
missing.sort_values("Percentage (%)", ascending=False)

                   Missing Values  Percentage (%)
CancellationCode          1979780           98.99
CarrierDelay              1778197           88.91
WeatherDelay              1778197           88.91
NASDelay                  1778197           88.91
SecurityDelay             1778197           88.91
LateAircraftDelay         1778197           88.91
ArrDelay                    41078            2.05
ArrDelayMinutes             41078            2.05
DepDelay                    36068            1.80
DepDelayMinutes             36068            1.80
OriginState                   646            0.03
DestState                     594            0.03

In [26]:
#Duplicate Rows
duplicate_rows = df[df.duplicated()]
duplicate_rows_count = duplicate_rows.shape[0]
print(f"Duplicate Rows : {duplicate_rows_count}")

Duplicate Rows : 548

In [27]:
#Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 27 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Quarter            int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   FlightDate         object
 6   Reporting_Airline  object
 7   Origin             object
 8   OriginCityName     object
 9   OriginState        object
 10  Dest               object
 11  DestCityName       object
 12  DestState          object
 13  DepDelay           float64
 14  DepDelayMinutes    float64
 15  ArrDelay           float64
 16  ArrDelayMinutes    float64
 17  CarrierDelay       float64
 18  WeatherDelay       float64
 19  NASDelay           float64
 20  SecurityDelay      float64
 21  LateAircraftDelay  float64
 22  Cancelled          float64
 23  CancellationCode   object
 24  Diverted           float64
 25  Distance           float64
 26  DistanceGroup      int64
dtypes: float64(12), int64(6), object(9)
memory usage: 412.0+ MB

In [28]:
# Statistical Summary of Numerical Columns
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,2000000.0,2004.313701,9.228930,1987.0,1997.0,2005.0,2012.0,2020.0
Quarter,2000000.0,2.501267,1.118022,1.0,1.0,3.0,3.0,4.0
Month,2000000.0,6.500761,3.443460,1.0,3.0,7.0,9.0,12.0
DayofMonth,2000000.0,15.722019,8.778412,1.0,8.0,16.0,23.0,31.0
DayOfWeek,2000000.0,3.937445,1.990369,1.0,2.0,4.0,6.0,7.0
DepDelay,1963932.0,8.587405,32.724728,-990.0,-3.0,0.0,7.0,1878.0
DepDelayMinutes,1963932.0,10.496667,31.964667,0.0,0.0,0.0,7.0,1878.0
ArrDelay,1958922.0,6.205467,34.833399,-706.0,-10.0,-1.0,10.0,1898.0
ArrDelayMinutes,1958922.0,11.794417,31.971210,0.0,0.0,0.0,10.0,1898.0
CarrierDelay,221803.0,16.892580,46.222289,0.0,0.0,0.0,17.0,1878.0
WeatherDelay,221803.0,2.939929,21.101110,0.0,0.0,0.0,0.0,1847.0
NASDelay,221803.0,15.389395,30.538782,0.0,0.0,4.0,19.0,1343.0
SecurityDelay,221803.0,0.084873,2.109449,0.0,0.0,0.0,0.0,219.0
LateAircraftDelay,221803.0,22.054170,41.631429,0.0,0.0,0.0,27.0,1407.0
Cancelled,2000000.0,0.018231,0.133786,0.0,0.0,0.0,0.0,1.0
Diverted,2000000.0,0.002295,0.047851,0.0,0.0,0.0,0.0,1.0
Distance,2000000.0,733.496272,568.496786,11.0,325.0,580.0,967.0,5095.0
DistanceGroup,2000000.0,3.409396,2.242753,1.0,2.0,3.0,4.0,11.0

In [29]:
# Statistical Summary of Categorical Columns
df.describe(include="object").T

                     count unique          top    freq
FlightDate         2000000  11871   2019-07-22     264
Reporting_Airline  2000000     33           WN  306238
Origin             2000000    406          ATL  108667
OriginCityName     2000000    400  Chicago, IL  125262
OriginState        1999354     53           CA  235509
Dest               2000000    408          ATL  108112
DestCityName       2000000    403  Chicago, IL  125466
DestState          1999406     53           CA  235341
CancellationCode     20220      4            B    8469

In [30]:
# Drop rows with missing OriginState or DestState
df.dropna(subset=["OriginState", "DestState"], inplace=True)

In [31]:
delay_columns = [
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay"
]

df[delay_columns] = df[delay_columns].fillna(0)

In [32]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": round(df.isnull().mean() * 100, 2)
})

missing = missing[missing["Missing Values"] > 0]
missing.sort_values("Percentage (%)", ascending=False)

                  Missing Values  Percentage (%)
CancellationCode         1978735           98.99
ArrDelay                   41052            2.05
ArrDelayMinutes            41052            2.05
DepDelay                   36048            1.80
DepDelayMinutes            36048            1.80

In [33]:
# Convert FlightDate to datetime
df["FlightDate"] = pd.to_datetime(df["FlightDate"])

In [34]:
# Convert categorical columns to category dtype
categorical_columns = [
    "Reporting_Airline",
    "Origin",
    "OriginCityName",
    "OriginState",
    "Dest",
    "DestCityName",
    "DestState",
    "CancellationCode"
]

for col in categorical_columns:
    df[col] = df[col].astype("category")

In [35]:
# Dataset information
df.info()

# Check for remaining duplicates
print("Duplicate Records:", df.duplicated().sum())

# Verify missing values
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": round(df.isnull().mean() * 100, 2)
})

missing[missing["Missing Values"] > 0]

<class 'pandas.core.frame.DataFrame'>
Index: 1998955 entries, 0 to 1999999
Data columns (total 27 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Quarter            int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   FlightDate         datetime64[ns]
 6   Reporting_Airline  category
 7   Origin             category
 8   OriginCityName     category
 9   OriginState        category
 10  Dest               category
 11  DestCityName       category
 12  DestState          category
 13  DepDelay           float64
 14  DepDelayMinutes    float64
 15  ArrDelay           float64
 16  ArrDelayMinutes    float64
 17  CarrierDelay       float64
 18  WeatherDelay       float64
 19  NASDelay           float64
 20  SecurityDelay      float64
 21  LateAircraftDelay  float64
 22  Cancelled          float64
 23  CancellationCode   category
 24  Diverted           float64
 25  Distance           float64
 26  DistanceGroup      int64
dtypes: category(8), datetime64[ns](1), float64(12), int64(6)
memory usage: 328.0 MB
Duplicate Records: 548

                  Missing Values  Percentage (%)
DepDelay                   36048            1.80
DepDelayMinutes            36048            1.80
ArrDelay                   41052            2.05
ArrDelayMinutes            41052            2.05
CancellationCode         1978735           98.99

In [36]:
df.to_csv(
    "../dataset/processed/airline_delay_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Key Observations

- Missing values in delay reason columns were replaced with `0` as they indicate that the corresponding delay did not occur.
- Rows with missing origin or destination state information were removed due to their negligible impact on the dataset.
- Remaining missing values were retained because they represent valid operational scenarios such as cancelled or diverted flights.
- The `FlightDate` column was converted to a datetime format, and categorical columns were optimized to improve memory efficiency.
- The cleaned dataset is now ready for exploratory data analysis.